require 'rubygems'
require 'rest_connection'
require 'google_spreadsheet'
require 'fog'
require 'json'

require 'cpk/extract.rb'
require 'cpk/credentials.rb'
require 'cpk/deployments.rb'
require 'cpk/ssh.rb'
require 'cpk/s3.rb'
require 'cpk/build.rb'
require 'cpk/securitygroup.rb'
require 'cpk/config.rb'
require 'cpk/eip.rb'
